#!/bin/bash
cat /var/log/anaconda/X.log | grep -E "\\] \\(WW\\)" | sed s/\(WW\)/"Warning"\:/ >full.log
cat /var/log/anaconda/X.log | grep -E "\\] \\(WW\\)" | sed s/\(II\)/"Infirmation"\:/ >> full.log
