#!/bin/bash
mail="[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)*@[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*\\.[a-zA-Z]+"
grep --extended-regexp —-only-matching -—no-messages -—no-filename —-word-regexp $mail /etc/* | \
awk '{printf("$s, ".$1)}' | sed s/,$// > email.list
